### ISSUE TITLE
Error running with python >= 3.10 

### ISSUE THREAD

**Issue by naveenk93** [WazirX/wazirx-connector-python#13]
If you invoke this API with python 3.10 or higher, it throws exception.

Traceback (most recent call last):
  File "c:\Users\magic\Documents\app.py", line 1, in <module>
    from wazirx_sapi_client.rest import Client
  File "c:\Users\magic\Documents\wazirx_sapi_client\rest\__init__.py", line 4, in <module>
    raise BaseException("Python>=3.7 required")

**Comment by abhijitgawai** [comment]
Python>=3.7 required
Clearly mentioned in Exception.
You need to upgrade your Python version

**Comment by abhijitgawai** [comment]
Please change the __init__.py file. Take reference from below PR.
https://github.com/WazirX/wazirx-connector-python/pull/18
Tx
