### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by MPaandeey** [WazirX/wazirx-connector-python#14]
when I run a test file and I got an error
`Traceback (most recent call last):
  File "e:\Code\wazirx-connector-python-master\wazirx_sapi_client\rest\test.py", line 9, in <module>        
    from wazirx_sapi_client.rest import Client
  File "e:\Code\wazirx-connector-python-master\wazirx_sapi_client\rest\__init__.py", line 4, in <module>    
    raise BaseException("Python>=3.7 required")
BaseException: Python>=3.7 required`

**Comment by aakashH242** [comment]
This is not an Import Error. As you can clearly see in the error message, this library requires at least python version 3.7 to run.
Please ensure your python version is 3.7 or greater.

**Comment by abhijitgawai** [comment]
Please change the __init__.py file. Take reference from below PR.
https://github.com/WazirX/wazirx-connector-python/pull/18
Tx
